name: farmers
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://doctorai/object-detection-api:latest
    steps:
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          
