name: farmers
on: [push]
jobs:
  run:
    runs-on: [self-hosted]
    steps:
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo hello world
          docker run --rm -i -t=false doctorai/object-detection-api /bin/bash
          
