name: farmers
on: [push]
jobs:
  run:
    runs-on: [self-hosted]
    container: docker://doctorai/object-detection-api:latest
    steps:
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo hello world
          pip install -r requirements.txt
          
